version: "3"
services:
  reverseproxy:
    build:
      context: ../../udagram-reverse-proxy
    image: dieserwindikus/udagram-reverseproxy
  backend_user:
    build:
      context: ../../udagram-api-user
    image: dieserwindikus/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: dieserwindikus/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: dieserwindikus/udagram-frontend